name: Tests

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up latest Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run Tests
        run: |
          python -m pytest EleMD/tests.py
